# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(287, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(33, 12, 224, 244))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.second_bid_time = QtWidgets.QTimeEdit(self.widget)
        self.second_bid_time.setMaximumTime(QtCore.QTime(11, 29, 59))
        self.second_bid_time.setMinimumTime(QtCore.QTime(11, 29, 0))
        self.second_bid_time.setCurrentSection(QtWidgets.QDateTimeEdit.SecondSection)
        self.second_bid_time.setCurrentSectionIndex(2)
        self.second_bid_time.setObjectName("second_bid_time")
        self.gridLayout.addWidget(self.second_bid_time, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.second_bid_price = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_bid_price.sizePolicy().hasHeightForWidth())
        self.second_bid_price.setSizePolicy(sizePolicy)
        self.second_bid_price.setMinimum(0)
        self.second_bid_price.setMaximum(2000)
        self.second_bid_price.setSingleStep(100)
        self.second_bid_price.setObjectName("second_bid_price")
        self.gridLayout.addWidget(self.second_bid_price, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.third_bid_time = QtWidgets.QTimeEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.third_bid_time.setFont(font)
        self.third_bid_time.setMaximumTime(QtCore.QTime(11, 29, 59))
        self.third_bid_time.setMinimumTime(QtCore.QTime(11, 29, 0))
        self.third_bid_time.setCurrentSection(QtWidgets.QDateTimeEdit.SecondSection)
        self.third_bid_time.setCurrentSectionIndex(2)
        self.third_bid_time.setObjectName("third_bid_time")
        self.gridLayout.addWidget(self.third_bid_time, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.third_bid_price = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_bid_price.sizePolicy().hasHeightForWidth())
        self.third_bid_price.setSizePolicy(sizePolicy)
        self.third_bid_price.setMinimum(0)
        self.third_bid_price.setMaximum(2000)
        self.third_bid_price.setSingleStep(100)
        self.third_bid_price.setObjectName("third_bid_price")
        self.gridLayout.addWidget(self.third_bid_price, 4, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 3)
        self.force_bid = QtWidgets.QCheckBox(self.widget)
        self.force_bid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.force_bid.setObjectName("force_bid")
        self.gridLayout.addWidget(self.force_bid, 6, 0, 1, 2)
        self.force_bid_time = QtWidgets.QTimeEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.force_bid_time.setFont(font)
        self.force_bid_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(11, 29, 59)))
        self.force_bid_time.setMaximumTime(QtCore.QTime(11, 30, 0))
        self.force_bid_time.setMinimumTime(QtCore.QTime(11, 29, 0))
        self.force_bid_time.setCurrentSection(QtWidgets.QDateTimeEdit.MSecSection)
        self.force_bid_time.setDisplayFormat("HH:mm:ss.zzz")
        self.force_bid_time.setCurrentSectionIndex(3)
        self.force_bid_time.setTime(QtCore.QTime(11, 29, 59))
        self.force_bid_time.setObjectName("force_bid_time")
        self.gridLayout.addWidget(self.force_bid_time, 7, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(28, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "策略选择"))
        self.label_2.setText(_translate("MainWindow", "第二次出价"))
        self.second_bid_time.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.label_6.setText(_translate("MainWindow", "+"))
        self.label_5.setText(_translate("MainWindow", "第三次出价"))
        self.third_bid_time.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.label_4.setText(_translate("MainWindow", "+"))
        self.force_bid.setText(_translate("MainWindow", "使用强制提交"))
        self.pushButton.setText(_translate("MainWindow", "确定"))


