# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(322, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(33, 12, 269, 262))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.thirdBidPrice = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thirdBidPrice.sizePolicy().hasHeightForWidth())
        self.thirdBidPrice.setSizePolicy(sizePolicy)
        self.thirdBidPrice.setMinimum(0)
        self.thirdBidPrice.setMaximum(2000)
        self.thirdBidPrice.setSingleStep(100)
        self.thirdBidPrice.setObjectName("thirdBidPrice")
        self.gridLayout.addWidget(self.thirdBidPrice, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(28, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.confirmButton = QtWidgets.QPushButton(self.layoutWidget)
        self.confirmButton.setObjectName("confirmButton")
        self.gridLayout.addWidget(self.confirmButton, 9, 0, 1, 1)
        self.advancedButton = QtWidgets.QPushButton(self.layoutWidget)
        self.advancedButton.setObjectName("advancedButton")
        self.gridLayout.addWidget(self.advancedButton, 9, 2, 1, 1)
        self.secondBidTime = QtWidgets.QTimeEdit(self.layoutWidget)
        self.secondBidTime.setMaximumTime(QtCore.QTime(11, 29, 59))
        self.secondBidTime.setMinimumTime(QtCore.QTime(11, 29, 0))
        self.secondBidTime.setCurrentSection(QtWidgets.QDateTimeEdit.SecondSection)
        self.secondBidTime.setCurrentSectionIndex(2)
        self.secondBidTime.setObjectName("secondBidTime")
        self.gridLayout.addWidget(self.secondBidTime, 2, 0, 1, 1)
        self.secondBidPrice = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondBidPrice.sizePolicy().hasHeightForWidth())
        self.secondBidPrice.setSizePolicy(sizePolicy)
        self.secondBidPrice.setMinimum(0)
        self.secondBidPrice.setMaximum(2000)
        self.secondBidPrice.setSingleStep(100)
        self.secondBidPrice.setObjectName("secondBidPrice")
        self.gridLayout.addWidget(self.secondBidPrice, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 2, 1)
        self.thirdBidTime = QtWidgets.QTimeEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thirdBidTime.setFont(font)
        self.thirdBidTime.setMaximumTime(QtCore.QTime(11, 29, 59))
        self.thirdBidTime.setMinimumTime(QtCore.QTime(11, 29, 0))
        self.thirdBidTime.setCurrentSection(QtWidgets.QDateTimeEdit.SecondSection)
        self.thirdBidTime.setCurrentSectionIndex(2)
        self.thirdBidTime.setObjectName("thirdBidTime")
        self.gridLayout.addWidget(self.thirdBidTime, 4, 0, 1, 1)
        self.forceBidTime = QtWidgets.QTimeEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.forceBidTime.setFont(font)
        self.forceBidTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(11, 29, 59)))
        self.forceBidTime.setMaximumTime(QtCore.QTime(11, 30, 0))
        self.forceBidTime.setMinimumTime(QtCore.QTime(11, 29, 0))
        self.forceBidTime.setCurrentSection(QtWidgets.QDateTimeEdit.MSecSection)
        self.forceBidTime.setDisplayFormat("HH:mm:ss.zzz")
        self.forceBidTime.setCurrentSectionIndex(3)
        self.forceBidTime.setTime(QtCore.QTime(11, 29, 59))
        self.forceBidTime.setObjectName("forceBidTime")
        self.gridLayout.addWidget(self.forceBidTime, 7, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.forceBid = QtWidgets.QCheckBox(self.layoutWidget)
        self.forceBid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.forceBid.setObjectName("forceBid")
        self.gridLayout.addWidget(self.forceBid, 6, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.productWeb = QtWidgets.QPushButton(self.layoutWidget)
        self.productWeb.setEnabled(True)
        self.productWeb.setObjectName("productWeb")
        self.gridLayout.addWidget(self.productWeb, 10, 0, 1, 1)
        self.testWeb = QtWidgets.QPushButton(self.layoutWidget)
        self.testWeb.setObjectName("testWeb")
        self.gridLayout.addWidget(self.testWeb, 10, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 3)
        MainWindow.setCentralWidget(self.widget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.confirmButton.clicked.connect(MainWindow.confirmButtonClick)
        self.productWeb.clicked.connect(MainWindow.formalPpClick)
        self.testWeb.clicked.connect(MainWindow.testPpClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "熊猫拍牌"))
        self.label_5.setText(_translate("MainWindow", "第三次出价"))
        self.confirmButton.setText(_translate("MainWindow", "确定"))
        self.advancedButton.setText(_translate("MainWindow", "高级设置"))
        self.secondBidTime.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.label.setText(_translate("MainWindow", "策略选择"))
        self.thirdBidTime.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.label_4.setText(_translate("MainWindow", "  +"))
        self.forceBid.setText(_translate("MainWindow", "使用强制提交"))
        self.label_2.setText(_translate("MainWindow", "第二次出价"))
        self.label_6.setText(_translate("MainWindow", "  +"))
        self.productWeb.setText(_translate("MainWindow", "正式拍牌"))
        self.testWeb.setText(_translate("MainWindow", "测试拍牌"))


